cpu_usage_threshold: 60    # CPU usage threshold in percentage
memory_usage_threshold: 80 # Memory usage threshold in percentage
disk_usage_threshold: 70   # Disk usage threshold in percentage
interval_seconds: 5        # Interval for checking metrics, default 5 seconds
