cpu_usage_threshold: 80    # CPU usage threshold in percentage
memory_usage_threshold: 80 # Memory usage threshold in percentage
disk_usage_threshold: 80   # Disk usage threshold in percentage
interval_seconds: 60       # Interval for checking metrics, default 5 seconds
log_directory: ""          # Log directory (default is current directory)
google_sheet_id: ""        # Google Sheet ID